sylius_resource:
    resources:
        monsieurbiz_menu.menu:
            classes:
                model: MonsieurBiz\SyliusMenuPlugin\Entity\Menu
                form: MonsieurBiz\SyliusMenuPlugin\Form\Type\MenuType
                repository: MonsieurBiz\SyliusMenuPlugin\Repository\MenuRepository
        monsieurbiz_menu.menu_item:
            classes:
                model: MonsieurBiz\SyliusMenuPlugin\Entity\MenuItem
                form: MonsieurBiz\SyliusMenuPlugin\Form\Type\MenuItemType
                repository: MonsieurBiz\SyliusMenuPlugin\Repository\MenuItemRepository
                controller: MonsieurBiz\SyliusMenuPlugin\Controller\MenuItemResourceController
            translation:
                classes:
                    model: MonsieurBiz\SyliusMenuPlugin\Entity\MenuItemTranslation
                    form: MonsieurBiz\SyliusMenuPlugin\Form\Type\MenuItemTranslationType
