sylius_ui:
    events:
        monsieurbiz_menu.admin.menu.update.items_tree:
            blocks:
                items_tree:
                    template: '@MonsieurBizSyliusMenuPlugin/Admin/Menu/_treeWithButtons.html.twig'
        monsieurbiz_menu.admin.menu_item.create.items_tree:
            blocks:
                items_tree:
                    template: '@MonsieurBizSyliusMenuPlugin/Admin/Menu/_treeWithButtons.html.twig'
        monsieurbiz_menu.admin.menu_item.update.items_tree:
            blocks:
                items_tree:
                    template: '@MonsieurBizSyliusMenuPlugin/Admin/Menu/_treeWithButtons.html.twig'
        monsieurbiz_menu.admin.menu.update.after_content:
            blocks:
                menu_js:
                    template: '@MonsieurBizSyliusMenuPlugin/Admin/Menu/_js.html.twig'
        monsieurbiz_menu.admin.menu_item.update.after_content:
            blocks:
                menu_js:
                    template: '@MonsieurBizSyliusMenuPlugin/Admin/Menu/_js.html.twig'
        monsieurbiz_menu.admin.menu_item.create.after_content:
            blocks:
                menu_js:
                    template: '@MonsieurBizSyliusMenuPlugin/Admin/Menu/_js.html.twig'
        sylius.shop.layout.header:
            blocks:
                menu:
                    template: '@MonsieurBizSyliusMenuPlugin/Layout/Header/_menu.html.twig'   
        sylius.shop.layout.footer.grid:
            blocks:
                your_store: 
                    template: '@MonsieurBizSyliusMenuPlugin/Layout/Footer/Grid/_your_store.html.twig'
                customer_care:
                    template: '@MonsieurBizSyliusMenuPlugin/Layout/Footer/Grid/_customer_care.html.twig'
